# Dependencies must also be addded to LicensesDialog.java

[versions]
morphe-patcher = "1.14.0"
morphe-patches-library = "1.8.0-dev.1"
# Tracking https://github.com/google/smali/issues/100.
smali = "d92701d947"
agp = "9.1.0"
annotation = "1.10.0"
androidx-core = "1.18.0"    # 1.19.0+ requires upgrading android compile sdk
androidx-javascriptengine = "1.1.0"
collections4 = "4.6.0"
gson = "2.14.0"
lang3 = "3.20.0"
guava = "33.6.0-jre"
hiddenapi = "6.1"
protobuf = "0.10.0"
protoc = "4.36.2"

[libraries]
morphe-patches-library = { module = "app.morphe:morphe-patches-library", version.ref = "morphe-patches-library" }
morphe-extensions-library = { module = "app.morphe:morphe-extensions-library", version.ref = "morphe-patches-library" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-javascriptengine = { module = "androidx.javascriptengine:javascriptengine", version.ref = "androidx-javascriptengine" }
collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "collections4" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "lang3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hiddenapi = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapi" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoc" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }

[plugins]
android-library = { id = "com.android.library" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
